---
repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
# FIXME: doesn't work properly on NTFS managed shares.
#      - id: check-executables-have-shebangs

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
    - id: forbid-binary
# TODO: activate in later release
#    - id: rubocop
# FIXME: doesn't work properly on NTFS managed shares.
#    - id: script-must-have-extension
#    - id: script-must-not-have-extension
    - id: shellcheck
      additional_dependencies: []

# TODO: activate in later release
#  - repo: https://github.com/pre-commit/mirrors-ruby-lint
#    rev: v2.3.1-1
#    hooks:
#    - id: ruby-lint
