---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: terraformmoduleoutputs
  name: terraform module outpts
  description: Add computed module outputs using terraform-config-inspect
  entry: hooks/createmoduleoutputs.rb
  language: ruby
  pass_filenames: false
  files: (\.tf|\.tfvars|\.tf\.json|\.tfvars\.json)$
  exclude: \.terraform\/.*$
