---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: terraformmoduleoutputs
  name: terraform module outputs
  description: Add computed module outputs using terraform-config-inspect.
  entry: createmoduleoutputs.rb
  language: ruby
  pass_filenames: false
  files: (\.tf|\.tfvars|\.tf\.json|\.tfvars\.json)$
  exclude: \.terraform\/.*$

- id: terraformcreatei2o
  name: terraform module createi2o
  description: Add module inputs as outputs to the module.
  entry: hooks/createi2o.sh
  language: script
  pass_filenames: false
  files: (\.tf|\.tfvars|\.tf\.json|\.tfvars\.json)$
  exclude: \.terraform\/.*$
